# Cadastrar usuário:
POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "astrodev",
    "email": "astrodev@email.com",
    "password": "123456"
}

###

# Login:
POST http://localhost:3003/login
Content-Type: application/json

{
    "email": "astrodev@email.com",
    "password": "123456"
}

###

# Fazer amizade:
POST http://localhost:3003/add/ae9d4286-4874-44ee-9c51-8515df3f7dd2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM5YzJhYWZjLWYzMmUtNDdlYi04YjMyLTgxMTllNDQ0MTQ5OSIsImlhdCI6MTY1MTgzNzYxNCwiZXhwIjoxNjUxODU1NjE0fQ.TU7XRCugb503qFmD8siY_oY2tD-NqM3JWuF8CyeQGTI

###

# Desfazer amizade:
DELETE http://localhost:3003/unfriend/ae9d4286-4874-44ee-9c51-8515df3f7dd2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM5YzJhYWZjLWYzMmUtNDdlYi04YjMyLTgxMTllNDQ0MTQ5OSIsImlhdCI6MTY1MTgzNzYxNCwiZXhwIjoxNjUxODU1NjE0fQ.TU7XRCugb503qFmD8siY_oY2tD-NqM3JWuF8CyeQGTI

###

# Ver todo o feed:
GET http://localhost:3003/feed
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM5YzJhYWZjLWYzMmUtNDdlYi04YjMyLTgxMTllNDQ0MTQ5OSIsImlhdCI6MTY1MTg0NDIxMCwiZXhwIjoxNjUxODYyMjEwfQ.HXxKCEThfkVSIfJkUl8q7aJxC0F5VVEHUzAHHPCIixk

###

# Ver apenas um tipo de post do feed:
GET http://localhost:3003/feed/normal
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM5YzJhYWZjLWYzMmUtNDdlYi04YjMyLTgxMTllNDQ0MTQ5OSIsImlhdCI6MTY1MTg0NDIxMCwiZXhwIjoxNjUxODYyMjEwfQ.HXxKCEThfkVSIfJkUl8q7aJxC0F5VVEHUzAHHPCIixk

###

# Buscar um post por id:
GET http://localhost:3003/post/184aa16d-535d-47d4-a0f3-72c8e4f40b94
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlOWQ0Mjg2LTQ4NzQtNDRlZS05YzUxLTg1MTVkZjNmN2RkMiIsImlhdCI6MTY1MTc3Njc3MSwiZXhwIjoxNjUxNzk0NzcxfQ.KsCUkReLtxFiToIO09ffrMGVOscaas7KpAvRi6oPZ0w

###

# Criar post:
POST http://localhost:3003/post
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlOWQ0Mjg2LTQ4NzQtNDRlZS05YzUxLTg1MTVkZjNmN2RkMiIsImlhdCI6MTY1MTY5MDg5MSwiZXhwIjoxNjUxNzA4ODkxfQ.xhZIesrM59cmeGtJt3X8zbtcp7UsM_DPYyrXL-MTxcE
Content-Type: application/json

{
    "photo": "urlDaFoto",
    "description": "Foto do meu cachorro!",
    "type": "Normal"
}

###

# Comentar no post:
POST http://localhost:3003/comment/184aa16d-535d-47d4-a0f3-72c8e4f40b94
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlOWQ0Mjg2LTQ4NzQtNDRlZS05YzUxLTg1MTVkZjNmN2RkMiIsImlhdCI6MTY1MTg2MTk5NywiZXhwIjoxNjUxODc5OTk3fQ.yN1Dcq67UlGw_2jwIZIu5yjhSaohoUCtPYG26V3m5wY
Content-Type: application/json

{
    "comment": "Oie"
}

###

# Curtir post:
POST http://localhost:3003/post/184aa16d-535d-47d4-a0f3-72c8e4f40b94
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlOWQ0Mjg2LTQ4NzQtNDRlZS05YzUxLTg1MTVkZjNmN2RkMiIsImlhdCI6MTY1MTg1NzEyNSwiZXhwIjoxNjUxODc1MTI1fQ.Kx9KD2dEgL98yEmNgcmXZrMIN52IaT_RXmu5RfhR2go

###

# Descurtir post:
PUT http://localhost:3003/post/184aa16d-535d-47d4-a0f3-72c8e4f40b94
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlOWQ0Mjg2LTQ4NzQtNDRlZS05YzUxLTg1MTVkZjNmN2RkMiIsImlhdCI6MTY1MTg1ODI0OCwiZXhwIjoxNjUxODc2MjQ4fQ.7D0YF2AU8SzUZUth9KHfh-xLM4lE83m5agSJ6Nk7J3Y